name: Deploy DNS Monitor

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/dns-monitor
            export GRAFANA_ADMIN_USER="${{ secrets.GRAFANA_USERNAME }}"
            export GRAFANA_ADMIN_PASSWORD="${{ secrets.GRAFANA_PASSWORD }}"
            docker compose pull
            docker compose up -d --force-recreate
